services:
  # Frontend - Static Site
  - type: web
    name: steampro-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://steampro-backend.onrender.com
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'

  - type: web
    name: steampro-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://steampro-frontend.onrender.com  # Direct URL instead of service reference
