services:
  - type: static_site  # Changed from 'web' to 'static_site' for frontend
    name: steampro-frontend
    buildCommand: npm install && npm run build
    outputDir: ./dist  # Changed from staticPublishPath to outputDir for static sites
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'

  - type: web
    name: steampro-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://steampro-frontend.onrender.com  # Direct URL instead of service reference
